### ISSUE TITLE
RSHELL  failed to access /dev/ttyUSB0

### ISSUE THREAD

**Issue by Novo55** [dhylands/rshell#40]
don't understand why RSHELL can't see my ESP32 when Picocom can.

rshell is version 0.0.11

Running Ububtu 16.04 on dell I7
![screenshot from 2018-01-05 16-20-58](https://user-images.githubusercontent.com/9299894/34596525-a0137a12-f234-11e7-899d-4bc32979ec68.png)

![screenshot from 2018-01-05 16-14-47](https://user-images.githubusercontent.com/9299894/34596471-0f42e842-f234-11e7-91c1-b5a4df120541.png)

**Comment by Novo55** [comment]
when I use sudo on the command it works, I'm such a newbie :-)

**Comment by dhylands** [comment]
There are two ways to make it so that you don't need to use sudo (and this is just a linux thing, nothing to do with rshell):
1 - Add your user to the dialout group. If you do `ls -l /dev/ttyUSB0` you'll typically see something like this:
```
crw-rw---- 1 root dialout 188, 0 Dec 18 20:54 /dev/ttyUSB0
```
This says that the user root and the group dialout have read/write access to /dev/ttyUSB0. Note, when adding yourself to a group, you'll need to logout completely and log back in for it to take effect. You can use the `id` command to verify what groups your user is a member of.

2 - You can add a file to /etc/udev/rules.d which will change the permissions of the /dev/ttyUSB0 file. Follow the directions here: https://github.com/micropython/micropython/wiki/Board-STM32F407-Discovery#programming-from-linux-via-dfu (note that you don't need to install dfu-utils)

**Comment by Novo55** [comment]
Hi Dave,


been using RSHELL for a couple of weeks its an awesome tool, please keep 
up the good work.

regards

-- 
regards Steve W

**Comment by tejastank** [comment]
# I face same issue.

sudo chmod 777 /dev/ttyUSB0

Above command works for me  ;)

**Comment by davehylands** [comment]
I added some notes to the rshell README: https://github.com/dhylands/rshell#serial-port-permissions-linux
